### ISSUE TITLE
Document usage of utilities to convert form values to signals

### ISSUE THREAD

**Issue by NateRadebaugh** [ngxtension/ngxtension-platform#365]
Signals are great but when I have a `computed` that relies on a form field value, there isn't a great way to trigger the re-compute.

I was thinking using `signalSlice` could provide form values from the formGroup:

```ts
formValues = signalSlice({
   initialState: this.formGroup.value,
   sources: [this.formGroup.valueChanges],
```

Is this supposed to work? Or is there a better way to set up a computed value that also uses a form value?

```ts
breadcrumbs = computed<BreadcrumbItem[]>(() => {
   // const subject = this.formGroup.controls.subject.value;
   const subject = this.formValues.subject();

   return [
      { label: "Home", to: "/" },
      {
        label: "App Announcement List",
        to: LIST_URL,
      },
      {
        label:
          "App Announcement Detail" +
          (subject
            ? ` - ${subject}`
            : ""),
      },
    ];
});
```

Would be great to have an example for this since I think the angular docs don't include anything regarding signals and forms together.

**Comment by joshuamorony** [comment]
You can use `signalSlice` in this way, though your example does need some small changes — I have a video covering this use case (and some other form stuff) here: https://youtu.be/cxoew5rmwFM?si=rgbYhBJVIvf_SN4U&t=90 (time code is linked to section showing setting up form value changes using signalSlice)

**Comment by NateRadebaugh** [comment]
🤯 yeah this is perfect. Great content to include in the docs as an example usage

**Comment by joshuamorony** [comment]
I'm currently looking at tidying up some things around signalSlice now, including the docs, so yeah will probably add some sort of "Example Patterns" section to the bottom of the docs

**Comment by michael-small** [comment]
I have been using Josh's approach in some work projects recently and it works really nice. You can also subscribe to status changes like the value utility in the video and then combine/map it to the signal slice. One word of advice: you want to throw in a `distinctUntilChange` like this `.distinctUntilChanged((a, b) => JSON.stringify(a) === JSON.stringify(b))` into the value and/or status change functions.

It works even better with reactive forms with the [new unified form events API](https://github.com/angular/angular/pull/54579) coming in v18. `dirty`/`touched` can now be reacted to and not just with status and value changes anymore. Here is [some functions I made with them like Josh's example](https://github.com/michael-small/unified-form-control-theorycrafting/blob/master/src/app/form-event-utils.ts), they are kind of all over the place at the moment.

I have proposed something like this in the discussions section of this project https://github.com/ngxtension/ngxtension-platform/discussions/334

**Comment by joshuamorony** [comment]
Interesting examples @michael-small going to take a closer look at those later — since you've been using signalSlice you might be interested in weighing in on these upcoming changes: (removing actionEffects and effects APIs): https://github.com/ngxtension/ngxtension-platform/pull/361 (adding replacement for actionEffects): https://github.com/ngxtension/ngxtension-platform/pull/363

**Comment by joshuamorony** [comment]
Getting the value changes in `sources` shouldn't be a problem, you should be able to convert your input signal to an observable and derive a stream of value changes to give to `sources` that way

The tricky part is the `initialState` because it needs to be set immediately, I'm not sure if there is a clever way to get around this now (probably not) but theoretically I think if I modified the API to allow passing in a `DestroyRef` and `Injector` it might be feasible to allow creating a `signalSlice` outside of constructor time

There's potentially some foot guns here though - if the signalSlice is tied to the context of the service/component it is contained in, and the `computed` runs again, I think previous `signalSlice` objects won't be cleaned up properly and their subscriptions will keep running.

Needing the `initialState` at constructor time might just be a hard limitation here.

**Comment by michael-small** [comment]
> Getting the value changes in sources shouldn't be a problem, you should be able to convert your input signal to an observable and derive a stream of value changes to give to sources that way

In my experience doing it like that is tricky, as the input is not considered initialized by the time you try to access the `.valueChanges`. It throws some error I can't recall at the moment, probably the same one that Nate gets. And with a normal decorator input, there is no error, but it seemingly doesn't react, as if it is a snapshot of the form just being initialized. To work around it... and it is probably a busted solution... I basically have a boolean subject and in the `ngOnInit` I `next` it to true and then when I want to get the form values I just filter for the subject to be true. 

> The tricky part is the initialState because it needs to be set immediately

Haven't had an issue with this using my subject approach, though I need to reference the same initial values const wherever needed.

> There's potentially some foot guns here though - if the signalSlice is tied to the context of the service/component it is contained in, and the computed runs again, I think previous signalSlice objects won't be cleaned up properly and their subscriptions will keep running.

Hmm good point I haven't thought about. I think before I invest more in the approach I aught to do some profiling (extra fancy console logs). For reference, we use the signal slice in our form service. Instantiate the form in there as well. Accessing a given control in a component is pretty easy, unless it happens to be an index in a FormArray. Like a whole form group in a component made for each group in an array. In that instance I pass the index as a signal input and then to get the form I use a computed with `$form = computed(() => this.formService.form.controls.formArray.at($this.index())`. That is the signalfied version, and for the sources end up doing `this.$form().valueChanges`. 

I am going to piece together a stackblitz as I troubleshoot this stuff and when it is ready I can share it in this thread.

**Comment by joshuamorony** [comment]
@michael-small the trick with using the input as a source will be to filter out any undefined values in the observable you create from the input signal, so the only thing it ever emits is a valid form control (this is just theory on my part though, I haven't actually tried this)

Can you link me to the subject approach you are talking about?

**Comment by michael-small** [comment]
@joshuamorony

1. Trying what I think you are suggesting like the video
2. The subject approach 

---

1)  I used your approach like the video of just `toObservable(this.$form)` and then working from there and it works. That said, here is an example of not just that approach working, but also commented out is what I am (and probably Nate) getting when trying to use the form as a signal input

https://stackblitz.com/edit/ptxmym?file=src%2Fapp%2Fparent%2Fparent.component.ts

Relevant part

```ts
export class ChildComponent {
  // I think I can still use this as a signal for the most part when I
  //     do not need to access its value/status streams, but I will just
  //     use the observable in this example's template for consistency
  $form = input.required<
    FormGroup<{
      name: FormControl<string | undefined>;
    }>
  >();

  // This is what I would naturally try
  //     However, try uncommenting
  //
  // badFormValue$ = this.$form().valueChanges;

  // However, this works fine
  form$ = toObservable(this.$form);
  formValue$ = this.form$.pipe(switchMap((form) => form.valueChanges));

  error = `vendor.js:38885 ERROR Error: NG0950: Input is required but no value is available yet. Find more at https://angular.io/errors/NG0950
  at ChildComponent.inputValueFn [as $form] (vendor.js:32616:13)
  at new ChildComponent (main.js:26:28)
  at NodeInjectorFactory.ChildComponent_Factory [as factory] (main.js:31:10)
  at getNodeInjectable (vendor.js:38340:38)
  at instantiateAllDirectives (vendor.js:43595:23)
  at createDirectivesInstances (vendor.js:43017:3)
  at ɵɵelementStart (vendor.js:54416:5)
  at Module.ɵɵelement (vendor.js:54473:3)
  at ParentComponent_Template (main.js:113:62)
  at executeTemplate (vendor.js:42983:5)`;
}
```

2) I don't think in comparison to the approach of (1) that this is that worth doing. Also I going to bed now so I rushed this. Check out Child B.

```ts
  formLoaded$ = new BehaviorSubject<boolean>(false);
  formValue$ = this.formLoaded$.pipe(
    filter(Boolean),
    switchMap(() => this.$form().valueChanges)
  );

  ngOnInit() {
    this.formLoaded$.next(true);
  }
```

**Comment by michael-small** [comment]
@NateRadebaugh you may like this https://github.com/ngxtension/ngxtension-platform/pull/391
