### ISSUE TITLE
npm install fails on CI environment

### ISSUE THREAD

**Issue by rezoled** [ngxtension/ngxtension-platform#392]
I have an NX repo which I upgrade to NX19, following that I updated to Angular 18 and ngxtension 3.3.0 as well.
While running npm i in our build environment I'm getting the following error:
```
npm error code 1
npm error path /runner/_work/rezonapp/rezonapp/node_modules/ngxtension/node_modules/nx
npm error command failed
npm error command sh -c node ./bin/post-install
npm error /runner/_work/rezonapp/rezonapp/node_modules/ngxtension/node_modules/nx/src/native/native-bindings.js:244
npm error     throw loadError
npm error     ^
npm error
npm error Error: Cannot find module '@nx/nx-linux-arm64-gnu'
npm error Require stack:
npm error - /runner/_work/rezonapp/rezonapp/node_modules/ngxtension/node_modules/nx/src/native/index.js
npm error - /runner/_work/rezonapp/rezonapp/node_modules/ngxtension/node_modules/nx/src/hasher/node-task-hasher-impl.js
npm error - /runner/_work/rezonapp/rezonapp/node_modules/ngxtension/node_modules/nx/src/hasher/task-hasher.js
npm error - /runner/_work/rezonapp/rezonapp/node_modules/ngxtension/node_modules/nx/src/hasher/hash-task.js
npm error - /runner/_work/rezonapp/rezonapp/node_modules/ngxtension/node_modules/nx/src/tasks-runner/run-command.js
npm error - /runner/_work/rezonapp/rezonapp/node_modules/ngxtension/node_modules/nx/src/nx-cloud/utilities/get-cloud-options.js
npm error - /runner/_work/rezonapp/rezonapp/node_modules/ngxtension/node_modules/nx/bin/post-install.js
npm error     at Module._resolveFilename (node:internal/modules/cjs/loader:[114](https://github.com/Rezonate-io/rezonapp/actions/runs/9269366892/job/25500026236#step:6:115)0:15)
npm error     at Function.resolve (node:internal/modules/helpers:188:19)
npm error     at Module._load (/runner/_work/rezonapp/rezonapp/node_modules/ngxtension/node_modules/nx/src/native/index.js:53:36)
npm error     at Module.require (node:internal/modules/cjs/loader:1231:19)
npm error     at require (node:internal/modules/helpers:177:18)
npm error     at Object.<anonymous> (/runner/_work/rezonapp/rezonapp/node_modules/ngxtension/node_modules/nx/src/native/native-bindings.js:213:31)
npm error     at Module._compile (node:internal/modules/cjs/loader:1364:14)
npm error     at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
npm error     at Module.load (node:internal/modules/cjs/loader:[120](https://github.com/Rezonate-io/rezonapp/actions/runs/9269366892/job/25500026236#step:6:121)3:32)
npm error     at Module._load (node:internal/modules/cjs/loader:1019:12) {
npm error   code: 'MODULE_NOT_FOUND',
npm error   requireStack: [
npm error     '/runner/_work/rezonapp/rezonapp/node_modules/ngxtension/node_modules/nx/src/native/index.js',
npm error     '/runner/_work/rezonapp/rezonapp/node_modules/ngxtension/node_modules/nx/src/hasher/node-task-hasher-impl.js',
npm error     '/runner/_work/rezonapp/rezonapp/node_modules/ngxtension/node_modules/nx/src/hasher/task-hasher.js',
npm error     '/runner/_work/rezonapp/rezonapp/node_modules/ngxtension/node_modules/nx/src/hasher/hash-task.js',
npm error     '/runner/_work/rezonapp/rezonapp/node_modules/ngxtension/node_modules/nx/src/tasks-runner/run-command.js',
npm error     '/runner/_work/rezonapp/rezonapp/node_modules/ngxtension/node_modules/nx/src/nx-cloud/utilities/get-cloud-options.js',
npm error     '/runner/_work/rezonapp/rezonapp/node_modules/ngxtension/node_modules/nx/bin/post-install.js'
npm error   ]
npm error }
npm error
npm error Node.js v18.20.3
```

**Comment by sysmat** [comment]
- same hare
- ngxtension@3.4.0 is using @nx/devkit@18.3.5
-  ngxtension should bump to @nx/devkit@19.1.1

**Comment by rezoled** [comment]
Btw, a workaround for this if you are stuck is to run NPM install with the —ignore-scripts flag, if after that you get a lot of errors because of missing modules than probably you will need to install them manually after running NPM install.

this is only temporary until this bug is fixed

**Comment by n-j-m** [comment]
Any movement on this issue? I'm getting this same error in our CI pipeline.
